# Generated by Django 3.1.5 on 2021-05-13 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_name', models.CharField(blank=True, max_length=300, null=True)),
                ('address_type', models.CharField(blank=True, choices=[('지명', 'REGION'), ('도로명', 'ROAD'), ('지번 주소', 'REGION_ADDR'), ('도로명 주소', 'ROAD_ADDR')], default='도로명 주소', max_length=11, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=100, null=True)),
                ('detail', models.CharField(blank=True, max_length=200, null=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('미입금', 'NON_DEPOSIT'), ('결제완료', 'PAYMENT_FINISHED'), ('출고', 'RELEASE'), ('배송완료', 'DELIVERY_COMPLETED'), ('반송중', 'RETURNING'), ('반송완료', 'RETURN_COMPLETED'), ('교환완료', 'EXCHANGE_COMPLETED'), ('환불완료', 'REFUND_COMPLETED')], default='미입금', max_length=20)),
                ('pay_method', models.CharField(blank=True, choices=[('KAKAO', 'KAKAO'), ('CASH', 'CASH')], default='CASH', max_length=20, null=True)),
                ('total_amount', models.PositiveIntegerField(default=0)),
                ('tid', models.CharField(blank=True, max_length=300, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('size', models.CharField(blank=True, max_length=10, null=True)),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='orders.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(choices=[('미출고', 'NON_RELEASE'), ('출고', 'RELEASE'), ('배송완료', 'DELIVERY_COMPLETED'), ('배송중', 'DELIVERING')], default='미출고', max_length=20)),
                ('message', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orders.address')),
                ('order_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=10, null=True)),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='products.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
